project_id = "emvwmwdsaakdnweyhmki"

[functions.keep-alive]
verify_jwt = false

[functions.get-latest-campaign-placement]
verify_jwt = false

[functions.public-landing-page]
verify_jwt = false

[functions.scheduled-updates]
verify_jwt = false